swagger: "2.0"
info:
  version: "1.0.0"
  title: Celo app API
  description: Celo App on Blockchain API documentation and test
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /hashingSpace:
    x-swagger-router-controller: hub
    post:
      summary: Generates users api key.
      description: Returns contracts transaction on success.
      operationId: addHashingSpace
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - in: formData
          name: logo
          type: file
          required: true
          description: PNG file of pixels.
        - in: formData
          name: name
          type: string
          required: true
          description: Api key name.
      responses:
        201:
          description: text successfully sent
        500:
          description: Internal Server Error
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
